spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/Develhope
    username: root
    password:
      driver-class-name: com.mysql.jbdc.Driver
    jpa:
      database: mysql
      show_sql: true
      hibernate:
      ddl-auto: create
